# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:51:00 2018 from module list in Acme::CPANLists::Import::PerlAdvent::2001_12_07 version 0.001.

package Acme::CPANModules::Import::PerlAdvent::2001_12_07;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://perladvent.org/2001/7th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",
  entries     => [{ module => "Scalar::Util" }],
  summary     => "Modules mentioned in Perl Advent Calendar 2001 (day 7)",
};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2001 (day 7)

