# This file was first automatically generated by gen-acme-cpanmodules-module-from-acme-cpanlists-list on Sat Sep 22 07:51:01 2018 from module list in Acme::CPANLists::Import::PerlAdvent::2001_12_17 version 0.001.

package Acme::CPANModules::Import::PerlAdvent::2001_12_17;

# DATE
# VERSION

our $LIST = {
  description => "This list is generated by extracting module names mentioned in [http://perladvent.org/2001/17th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",
  entries     => [{ module => "Attribute::TieClasses" }],
  summary     => "Modules mentioned in Perl Advent Calendar 2001 (day 17)",
};

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2001 (day 17)

